graphemes: ['-', a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, "\xE1", "\xE2", "\xE3", "\xE7", "\xE9", "\xEA",
  "\xED", "\xF1", "\xF3", "\xF4", "\xF5", "\xFA", "\xFC"]
phones: [A, A+, AX, A~, A~+, B, D, DJ, E, E+, E~, E~+, F, G, I, I+, IX, I~, I~+, K, L, LJ, M, N, NJ, O, O+, O~, O~+, P, R, RR, S, SCH, T, TJ, U, U+, UX, U~, U~+, V, W, W~, Z]
